import { Blocks, BookOpen, CalendarDays, Contact, GalleryHorizontal, Globe2, GraduationCap, LayoutPanelTop, ListChecks, MenuSquare, MessageSquareText, PanelTop, Quote, Settings2, Star, Users, type LucideIcon } from "lucide-react";

export type EditorField = { label: string; value?: string; type?: "text" | "textarea" | "url" | "image" | "toggle"; helper?: string };
export type EditorSection = { title: string; description: string; fields: EditorField[] };
export type EditorItem = { id: string; label: string; description: string; icon: LucideIcon; sections: EditorSection[] };

const text = (label: string, value: string): EditorField => ({ label, value });
const area = (label: string, value: string, helper?: string): EditorField => ({ label, value, type: "textarea", helper });
const url = (label: string, value: string): EditorField => ({ label, value, type: "url" });
const image = (label: string, value: string): EditorField => ({ label, value, type: "image", helper: "Upload a replacement or use a hosted image URL." });
const toggle = (label: string): EditorField => ({ label, type: "toggle" });

const section = (title: string, description: string, fields: EditorField[]): EditorSection => ({ title, description, fields });

export const siteEditors: EditorItem[] = [
  { id: "navbar", label: "Navbar", description: "Top ticker, branding, navigation links, social links and call-to-action", icon: MenuSquare, sections: [
    section("Brand identity", "Visible across desktop and mobile navigation.", [image("Logo / brand mark", "NMC"), text("College name", "National Multiple College"), text("Affiliation line", "Affiliated to CTEVT"), url("Logo destination", "/")]),
    section("Announcement & quick contact", "The dark top bar above the main navigation.", [toggle("Show announcement bar"), area("Ticker announcements", "Admissions Open for 2081/82 - Limited Seats Available, Apply Now\nRanked Among the Top CTEVT-Affiliated Technical Colleges in Nepal\nDiploma Programs in Civil, Computer and Electrical Engineering", "One announcement per line."), text("Quick phone", "+977-01-4XXXXXX"), text("Quick email", "info@nmc.edu.np"), toggle("Show quick contact on desktop")]),
    section("Navigation, CTA & social profiles", "Manage desktop links, dropdown entries and the mobile drawer.", [area("Main navigation", "About | #about\nAcademics | #academics\nAdmissions | #admissions\nFacilities | #campus\nEvents | #events\nContact | #contact", "One label and anchor per line."), area("Academics dropdown", "Diploma Programs | #programs\nCertificate Programs | #programs\nEngineering Faculty | #departments\nIT and Computing | #departments\nHealth Science | #departments"), text("CTA label", "Apply Now"), url("CTA URL", "#admissions"), area("Social profiles", "Facebook | https://facebook.com\nInstagram | https://instagram.com\nYouTube | https://youtube.com\nTikTok | https://tiktok.com\nWhatsApp | https://wa.me/977014000000")])
  ] },
  { id: "tab-bar", label: "Tab bar", description: "Browser tab title and favicon shown across the site", icon: Globe2, sections: [section("Browser tab", "Set the page title and favicon for the public site.", [text("Tab name", "National Multiple College - Affiliated to CTEVT"), image("Tab logo (favicon)", "/favicon.ico")])] },
  { id: "hero", label: "Hero slider", description: "Slideshow imagery, headline, calls-to-action and trust facts", icon: PanelTop, sections: [
    section("Hero content", "Text displayed over the five-slide hero.", [text("Admission badge", "Admissions Open - 2081/82 Academic Session"), text("Main heading", "Your Gateway to Technical Excellence"), text("Highlighted word", "Technical"), text("Affiliation eyebrow", "National Multiple College - Affiliated to CTEVT"), area("Description", "Join 3,500+ students pursuing industry-ready Diploma and Certificate programs in Engineering, IT, and Health Science at Nepal's leading CTEVT-affiliated technical college."), text("Primary button", "Explore Programs"), url("Primary URL", "#programs"), text("Secondary button", "Apply Now"), url("Secondary URL", "#admissions")]),
    section("Slides & behaviour", "Current implementation has five cinematic Ken Burns slides.", [image("Slide 1 - World-Class Campus", "https://images.unsplash.com/photo-1562774053-701939374585?w=1920&q=85&auto=format&fit=crop"), image("Slide 2 - Student-Centered Learning", "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1920&q=85&auto=format&fit=crop"), image("Slide 3 - Celebrating Excellence", "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1920&q=85&auto=format&fit=crop"), image("Slide 4 - Modern Technical Education", "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1920&q=85&auto=format&fit=crop"), image("Slide 5 - Research and Innovation", "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1920&q=85&auto=format&fit=crop"), toggle("Autoplay slider"), text("Slide duration (milliseconds)", "6000")])
  ] },
  { id: "stats", label: "Statistics bar", description: "Animated enrollment, program, faculty and experience counters", icon: ListChecks, sections: [section("Counter cards", "Each line produces a statistic below the hero.", [area("Statistics", "Enrolled Students | 3500 | +\nTechnical Programs | 20 | +\nQualified Faculty | 80 | +\nYears of Excellence | 28 | +", "label | numeric value | suffix"), toggle("Animate counters when visible")])] },
  { id: "about", label: "About section", description: "College story, feature image, establishment card, facts and action", icon: GraduationCap, sections: [section("About NMC", "The two-column content block at #about.", [image("About image", "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=900&q=80&auto=format&fit=crop"), text("Eyebrow", "About National Multiple College"), text("Heading", "Nepal's Trusted Technical Institute Since 1996"), area("First paragraph", "National Multiple College (NMC) is a premier CTEVT-affiliated technical institution committed to delivering practical, industry-relevant education in engineering, information technology, and health science."), area("Second paragraph", "With over 28 years of academic excellence, NMC has produced thousands of skilled graduates serving Nepal's development across construction, technology, healthcare, and beyond."), text("Establishment card", "1996 | Year of Establishment"), area("Fact cards", "Alumni Network | 3,500+\nIndustry Partners | 60+\nScholarship Recipients | 200+/yr\nPlacement Rate | 95%+"), text("Button label", "Our Story"), url("Button URL", "#about")])] },
  { id: "programs", label: "Programs", description: "CTEVT program heading, cards, badges and section action", icon: BookOpen, sections: [section("Program section", "Current program data shown on the public homepage.", [text("Eyebrow", "CTEVT Programs"), text("Heading", "Diploma and Certificate Programs"), area("Description", "All programs are approved by CTEVT and designed to deliver practical, career-focused training that meets national and international industry standards."), text("Button label", "View All Programs"), url("Button URL", "#programs")])] },
  { id: "why-nmc", label: "Why choose NMC", description: "Feature statements, accreditation image and proof point", icon: Star, sections: [section("Why choose NMC", "The dark #academics feature panel.", [text("Eyebrow", "Why Choose NMC"), text("Heading", "What Sets Us Apart from Other Colleges"), area("Introduction", "We do not just teach - we build careers. From government-approved CTEVT programs to industry-connected job placements, every aspect of NMC is designed to maximize your professional potential."), area("Features", "CTEVT Recognized and Government Approved\n95%+ Graduate Employment Rate\nModern Labs and Technical Workshops\nIndustry Exposure and On-the-Job Training"), image("Feature image", "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&q=80&auto=format&fit=crop"), text("Accreditation callout", "CTEVT Affiliated and Govt. Approved")])] },
  { id: "faculty", label: "Faculty", description: "Faculty heading, profile cards, photos, roles and ratings", icon: Users, sections: [section("Faculty profiles", "Individual entries map to the existing faculty card grid.", [text("Eyebrow", "Our Faculty"), text("Heading", "Learn from Experienced Professionals"), area("Description", "Our 80+ faculty members are qualified engineers, technical experts, and industry practitioners dedicated to your growth."), area("Faculty profiles", "Er. Ramesh Kumar Shrestha | Head of Department | Computer Engineering | 4.9\nEr. Sita Devi Adhikari | Senior Lecturer | Civil Engineering | 4.8\nEr. Bikash Raj Paudel | Lab Instructor | Electrical Engineering | 4.7\nMs. Anita Maharjan | Health Science Coordinator | Health Assistant | 4.9", "name | role | department | rating"), text("Button label", "Meet All Faculty"), url("Button URL", "#faculty")])] },
  { id: "events", label: "Events & news", description: "Events heading, date cards, categories and read links", icon: CalendarDays, sections: [section("Event cards", "Current events visible in the three-card grid.", [text("Eyebrow", "Events and News"), text("Heading", "What's Happening at NMC"), area("Events", "CTEVT Technical Skills Competition 2081 | 14 Aug | Competition\nOpen Day - Admissions 2081/82 | 22 Aug | Admissions\nAnnual Technical Exhibition and Project Fair | 05 Sep | Exhibition", "title | date | category"), text("View all label", "View All Events"), toggle("Show category badge"), toggle("Show Read More link")])] },
  { id: "testimonials", label: "Testimonials", description: "Graduate stories, profile images, quotes and ratings", icon: Quote, sections: [section("Student stories", "Graduate quote cards presented after the events section.", [text("Eyebrow", "Student Stories"), text("Heading", "Voices of Our Graduates"), area("Description", "Hear from students and alumni whose careers were launched by their NMC education."), area("Testimonials", "Sanjay Tamang | Diploma in Computer Engineering, 2080 | 5\nPriya Shrestha | Diploma in Health Assistant, 2079 | 5\nDipesh Karki | Diploma in Civil Engineering, 2080 | 5", "name | program | rating")])] },
  { id: "gallery", label: "Campus gallery", description: "Campus heading and five-image facilities mosaic", icon: GalleryHorizontal, sections: [section("Campus gallery", "Images for the public campus gallery.", [text("Eyebrow", "Campus and Facilities"), text("Heading", "Experience Life at NMC"), area("Description", "Modern technical labs, well-equipped workshops, and a student-focused campus designed for hands-on learning."), image("Gallery image 1", "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80&auto=format&fit=crop"), image("Gallery image 2", "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&q=80&auto=format&fit=crop"), image("Gallery image 3", "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80&auto=format&fit=crop"), image("Gallery image 4", "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600&q=80&auto=format&fit=crop"), image("Gallery image 5", "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&q=80&auto=format&fit=crop")])] },
  { id: "admissions", label: "Admissions CTA", description: "Admission campaign banner, CTAs and application facts", icon: MessageSquareText, sections: [section("Admission campaign", "Blue conversion section at #admissions.", [text("Urgency badge", "Admissions Closing Soon - 2081/82 Session"), text("Heading", "Begin Your Technical Career at NMC"), area("Description", "Enroll in Nepal's trusted CTEVT-affiliated college and gain the practical skills, recognized qualification, and industry connections that employers demand. Limited seats - apply today."), text("Primary button", "Apply for Admission"), url("Primary URL", "#contact"), text("Secondary button", "View Programs"), url("Secondary URL", "#programs"), area("Supporting facts", "Merit Scholarships Per Year | 200+\nApplication Deadline | Bhadra 2081\nCTEVT Approved Programs | 20+")])] },
  { id: "facilities", label: "Facilities strip", description: "Four compact campus facilities cards", icon: Blocks, sections: [section("Facility cards", "Informational strip directly above contact.", [area("Facilities", "Modern Computer Labs | High-speed networked computer labs with licensed software for all programs.\nCivil Drawing Hall | Fully equipped AutoCAD drawing hall for civil and architecture students.\nElectrical Workshops | Industry-grade electrical labs with hands-on training equipment.\nTechnical Library | Extensive CTEVT reference library with digital and print resources.")])] },
  { id: "contact", label: "Contact & enquiry", description: "Contact details, hours, social channels and enquiry form", icon: Contact, sections: [section("Contact information", "Details shown at #contact.", [text("Eyebrow", "Contact Us"), text("Heading", "We're Here to Help"), area("Description", "Have questions about admissions, programs, fees, or scholarships? Our team is ready to guide you every step of the way."), text("Address", "National Multiple College, Kathmandu, Nepal"), text("Phone / WhatsApp", "+977-01-4XXXXXX | +977-9800000000"), text("Email", "info@nmc.edu.np"), area("Office hours", "Sunday - Friday | 7:00 AM - 5:00 PM\nSaturday | 9:00 AM - 1:00 PM\nPublic Holidays | Closed")]), section("Enquiry form", "Field configuration and response UI; submissions will connect to the backend later.", [toggle("Enable enquiry form"), area("Visible fields", "Full Name (required)\nPhone Number (required)\nEmail Address\nProgram of Interest (required)\nMessage"), text("Submit button", "Send Enquiry"), area("Success message", "Thank you! Your enquiry has been received. We'll respond within 24 hours.")])] },
  { id: "footer", label: "Footer", description: "Brand block, link columns, newsletter and legal navigation", icon: LayoutPanelTop, sections: [section("Brand and newsletter", "Footer logo, copy and subscription UI.", [image("Footer brand mark", "NMC"), text("Brand name", "National Multiple College"), text("Affiliation line", "Affiliated to CTEVT"), area("Brand description", "Excellence in Technical and Vocational Education since 1996. Producing skilled, job-ready graduates for Nepal's development."), toggle("Enable newsletter"), text("Newsletter label", "Subscribe to updates"), text("Subscribe button", "Subscribe")]), section("Footer links", "Quick links, programs and legal items.", [area("Quick links", "About NMC\nCTEVT Affiliation\nAcademic Programs\nAdmissions 2081/82\nScholarships\nCampus Facilities"), area("Program links", "Diploma - Computer Engg.\nDiploma - Civil Engg.\nDiploma - Electrical Engg.\nDiploma - Electronics\nDiploma - Architecture\nDiploma - Health Assistant"), text("Copyright", "Copyright 2081 National Multiple College. All rights reserved. Affiliated to CTEVT."), area("Legal links", "Privacy Policy\nTerms of Use\nAccessibility\nSitemap")])] },
  { id: "site-settings", label: "Site settings", description: "Global metadata, favicon, colors and shared defaults", icon: Settings2, sections: [section("Global website settings", "Defaults shared across public pages.", [text("Site title", "National Multiple College - Affiliated to CTEVT"), area("Meta description", "National Multiple College (NMC) is a leading CTEVT-affiliated technical institute offering Diploma and Certificate programs in Engineering, IT, and Health Science."), area("SEO keywords", "National Multiple College, NMC, CTEVT, technical college Nepal, diploma engineering"), image("Favicon", "/favicon.ico"), text("Primary color", "#2563eb"), text("Secondary accent", "#0ea5e9"), text("Dark theme color", "#0f172a")])] }
];
